# Site settings
title: Lambdaspace
email: info@lambdaspace.gr
description: >
    Join a VC of H
baseurl: ""
url: "zeglisx.github.io/githubpages-boilerplate"
twitter_username: mozparticipate
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
